finalproj/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do
    resources :answers, except: [:index, :show, :new]
  end

  delete 'notifications', to: 'notifications#remove'
  post 'questions/:id/upvote', to: 'questions#upvote', as: :question_upvote
  post 'questions/:question_id/answers/:id/upvote', to: 'answers#upvote', as: :answer_upvote
  get 'search' => 'questions#search'
  get 'filter', to: 'questions#filter', as: :filter

  root 'questions#index'

  get 'profile/list' => 'profile#index'
  delete 'profile/:id/delete', to: 'profile#delete', as: :user_delete
  get 'profile/:id', to: 'profile#show', as: :user_profile
  post 'profile/:id', to: 'profile#update', as: :user_profile_update

end

finalproj/app/models/question.rb
class Question < ActiveRecord::Base
  # Form validations
  validates :title, 
  			presence: true
  validates :content,
  			presence: true

  # A question may have many answers submitted by users
  # Destroy answers on question delete
  has_many 	:answers, 
  			dependent: :destroy

  # Tags belong to a question to denote content
  has_many  :tags,
        dependent: :destroy

  # Relationship used to destroy notifications when question destroyed
  has_many :notifications,
        dependent: :destroy

  # A question belongs to the user that posted it
  belongs_to :user
end

finalproj/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy, :upvote]
  # set answers array to display on show for this question
  before_action :set_answers, only: [:show]
  # set tags array to display when showing this question
  before_action :set_tags, only: [:show]

  # User authentication to change questions
  before_action :authenticate_user!, except: [:index, :show, :search, :filter]
  # Ensure only the owner of the question can modify it
  before_action :confirm_owner, only: [:edit, :update, :destroy]

  # GET /questions
  def index
    @questions = Question.all.order(:id).reverse
  end

  # GET /questions/filter
  # Filters questions by tag and returns
  def filter
    @questions = []
    @category = params[:category]
    @category.downcase! unless @category.nil?

    Question.all.each do |q|
      q.tags.each do |t|
        if t.category == @category
          @questions.push(q)
        end
      end
    end unless @category.nil?

    if @category.nil?
      if params[:top]
        @questions = Question.all.order(:upvotes).reverse
      else
        @questions = Question.all.order(:id).reverse
      end
    end

    respond_to do |format|
      format.js {}
    end
  end

  #GET /search
  def search
    # Search content
    @content = params[:content]
    
    @foundqs = []

    # First check for tag, if it is a tag, list those questions
    Tag.all.each do |t|
	    if(t.category.downcase.include? @content)
		    @foundqs.push(Question.find(t.question_id))
	    end
    end  

    # Otherwise, check content and title of questions
    if(@foundqs.size <= 0) 
	    Question.all.each do |q|
		    #Check the content of the question
		    if(q.content.downcase.include? @content.downcase)
			   @foundqs.push(q)		
		    end	

		    #Check the title as well
		    if(q.title.downcase.include? @content.downcase and not @foundqs.include? q)
			   @foundqs.push(q)
		    end
      end
    end
    	

    #Then, Sort by upvotes first, then by answers
    @foundqs.sort_by!{|q| [q[:upvotes], q.answers.size]}#, q.answers.size]}#.reverse!()
    @foundqs.reverse!
  end

  # GET /questions/1
  def show
    # Blank answer object so a user can submit an answer
    @answer = Answer.new
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)
    # Current user owns this new question
    @question.user_id = current_user.id

    respond_to do |format|
      if @question.save
        # Build tag models for this question
        build_tags
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /questions/1
  def update
    respond_to do |format|
      if @question.update(question_params)
        # Rebuilds tags for this question
        build_tags
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
    end
  end

  # POST /questions/1/upvote
  def upvote
    @question.update(upvotes: @question.upvotes + 1)
    # Rep for question author
    @question.user.update(reputation: @question.user.reputation + 1)
    # Notification for question author
    Notification.create(user_id: @question.user.id, question_id: @question.id, content: 'Your question was upvoted!  Nice job!')
    
    redirect_to question_url(@question), notice: 'Question upvoted!'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    def set_answers
      @answers = Question.find(params[:id]).answers.order(:upvotes).reverse
    end

    def set_tags
      @tags = Question.find(params[:id]).tags
    end

    def confirm_owner
      if user_signed_in?
        unless current_user.isadmin
          if Question.find(params[:id]).user_id != current_user.id
            redirect_to questions_url, alert: 'You are not allowed to modify other user\'s questions.'
          end
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content)
    end

    # Builds tag model for each selected tag with this question as the owner
    def build_tags 
      # First flush all tags so a duplicate record doesn't occur
      Tag.delete(@question.tags)

      tobuild = params[:tags]
      tobuild.each do |category|
        Tag.create(question_id: @question.id, category: category)
      end unless tobuild.nil?
    end
end

finalproj/app/helpers/questions_helper.rb
module QuestionsHelper
end

finalproj/app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, size: 75 %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, size: "75x25" %>
  </div>
  <!-- Sends selected tags to build, hidden, set with the buttons -->
  <div class="field">
    <%= f.label :tags %><br>
    <%= select_tag :tags, options_for_select(Tag::TAG_OPTIONS), { multiple: true } %>
  </div>
  <% Tag::TAG_OPTIONS.each do |category| %>
    <div class="form-button-tags">
      <%= category %>
    </div>
  <% end %>
  <br id="clear-both">
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

finalproj/app/views/questions/_question.html.erb
<div id="question-wrapper">
  <span id="question-upvotes">
    <%= question.upvotes %><br>
    upvotes
    <% if !user_signed_in? || current_user.id != question.user_id %>
      <%= button_to 'Upvote!', question_upvote_path(question) %>
    <% end %>
  </span>
  <span id="question-answers">
    <%= question.answers.size %><br>
    answers
  </span>
  <div id="title-tags-wrap">
    <span id="question-title">
      <%= link_to(question) do %>
        <%= question.title %>
      <% end %>
    </span>
    <span id="question-tags">
      <% question.tags.each do |tag| %>
        <%= render tag %>
      <% end %>
    </span>
    <span id="question-author">
      asked by 
      <%= link_to user_profile_path(question.user) do %>
        <%= question.user.username %> 
      <% end %>
      (<%= question.user.reputation %>)
    </span>
  </div>
  <span id="question-mod-links">
    <% if user_signed_in? && (current_user.id == question.user_id || current_user.isadmin) %>
      <%= link_to 'Edit', edit_question_path(question) %>
    <% end %>
    <% if user_signed_in? && current_user.isadmin %>
      <%= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </span>
  <p id="question-preview"><%= question.content[0..150] %>...</p>
</div>

finalproj/app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

finalproj/app/views/questions/index.html.erb
<!-- User notifications, display with jQuery -->
<% if user_signed_in? && !current_user.notifications.empty? %>
  <div id="notifications">
    <ul>
      <% current_user.notifications.each do |notif| %>
        <%= render notif %>
      <% end %>
    </ul>
    <%= link_to 'Done', notifications_path, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>

<% if !user_signed_in? %>
  <p>Sign in to post a question!</p>
<% else %>
  <%= link_to 'Post Question', new_question_path %>
<% end %>

<div id="qlist-header">
    <p id="list-content">Questions</p>
    <%= link_to filter_path, remote: true do %>
      <p id="filter-button">all</p>
    <% end %>
    <%= link_to filter_path(top: true), remote: true do %>
      <p id="filter-button">top</p>
    <% end %>
</div>
<div id="index">
  <% @questions.each do |question| %>
    <%= render question %>
  <% end %>
</div>

finalproj/app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

finalproj/app/views/questions/search.html.erb
<!-- Displays search resutls -->

<br><br>
<div id="s-header">
	Search Content: "<%= @content %>"
</div>
<br><br><br>
<div id="search-content">
	<% if @foundqs.size > 0 %>
	<% @foundqs.each do |q| %>
	<%= render "question", question:  q%>
	<% end %>
	<% end %>
</div>

finalproj/app/views/questions/show.html.erb
<div id="qtitle">
  <%= @question.title %>
</div>
<hr>
<div id="qcontent-wrapper">
  <div id="qupvotes">
    <%= @question.upvotes %><br>
    upvotes
    <% if !user_signed_in? || current_user.id != @question.user_id %>
      <%= button_to 'Upvote!', question_upvote_path(@question) %>
    <% end %>
  </div>
  <div id="question-content">
    <%= @question.content %>
  </div>
  <div id="qlinks">
    <% if user_signed_in? && (current_user.id == @question.user_id || current_user.isadmin) %>
      <%= link_to 'Edit', edit_question_path(@question) %>
    <% end %>
    <% if user_signed_in? && current_user.isadmin %>
      <%= link_to 'Delete', @question, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div>
<div id="qtags">
  <% @question.tags.each do |tag| %>
    <%= render tag %>
  <% end %>
</div>
<div id="quser">
  <%= render @question.user %>
</div>

<hr id="clear-both">

<% unless @answers.empty? %>
  <p id="aheader"><%= @answers.length %> Answers</p>
  <% @answers.each do |ans| %>
    <%= render ans %>
    <hr>
  <% end %>
<% end %>

<% if !user_signed_in? %>
  <p>Sign in to add your answer!<p>
<% elsif current_user.id != @question.user_id %>
  <p>Submit a new answer...</p>
  <%= render 'answers/form' %>
<% end %>

<%= link_to 'Back', questions_path %>