finalproj/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do
    resources :answers, except: [:index, :show, :new]
  end

  delete 'notifications', to: 'notifications#remove'
  post 'questions/:id/upvote', to: 'questions#upvote', as: :question_upvote
  post 'questions/:question_id/answers/:id/upvote', to: 'answers#upvote', as: :answer_upvote
  get 'search' => 'questions#search'
  get 'filter', to: 'questions#filter', as: :filter

  root 'questions#index'

  get 'profile/list' => 'profile#index'
  delete 'profile/:id/delete', to: 'profile#delete', as: :user_delete
  get 'profile/:id', to: 'profile#show', as: :user_profile
  post 'profile/:id', to: 'profile#update', as: :user_profile_update

end

finalproj/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ask Mines</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1 id="header">
  <span id="root-link">
    <a href="/">Ask Mines</a>
  </span>
  <span id="header-buttons">
    <% if !user_signed_in? %>
      <%= button_to "log in", new_user_session_url, method: :get %>
      <%= button_to "sign up", new_user_registration_url, method: :get %>
    <% else %>
      <p id="welcome-message">Welcome <%= current_user.username %></p> 
      <%= button_to "sign out", destroy_user_session_url, method: :delete %>
      <%= button_to "profile", user_profile_path(current_user), method: :get %>
    <% end %>
    <%= button_to "users", profile_list_path, method: :get %>
    <!-- search button -->
    <input id='search-button' value='search' type='button'>
  </span>
</h1>

<!-- Search form, displays with jQuery -->
<div id="search-form">
  <%= form_tag("/search", method: :get) do %>
    <div class="field">
      <%= label_tag(:content, "Search for:") %>
      <%= text_field_tag :content %>
    </div>
    <div class="actions">
      <%= submit_tag("Search") %>
      <a id='search-close'>close</a>
    </div>
  <% end %>
</div>

<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<div id="wrapper">
  <div id="content">
    <%= content_for?(:devise) ? yield(:devise) : yield %>
  </div>
</div>

</body>
</html>