finalproj/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do
    resources :answers, except: [:index, :show, :new]
  end

  delete 'notifications', to: 'notifications#remove'
  post 'questions/:id/upvote', to: 'questions#upvote', as: :question_upvote
  post 'questions/:question_id/answers/:id/upvote', to: 'answers#upvote', as: :answer_upvote
  get 'search' => 'questions#search'
  get 'filter', to: 'questions#filter', as: :filter

  root 'questions#index'

  get 'profile/list' => 'profile#index'
  delete 'profile/:id/delete', to: 'profile#delete', as: :user_delete
  get 'profile/:id', to: 'profile#show', as: :user_profile
  post 'profile/:id', to: 'profile#update', as: :user_profile_update

end

finalproj/app/models/answer.rb
class Answer < ActiveRecord::Base
  # Answer belongs to one question
  belongs_to :question
  # Answer belongs to user that posted it
  belongs_to :user

  # Form validations
  validates :content,
  			presence: true
end

finalproj/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:edit, :update, :destroy, :upvote]
  # Set this answers question
  before_action :set_question

  # User authentication required for answer modification
  before_action :authenticate_user!
  # Can only modify answers that belong to the logged in user
  before_action :confirm_owner, except: [:create, :upvote]


  # GET questions/1/answers/1/edit
  def edit
  end

  # POST questions/1/answers
  def create
    @answer = Answer.new(answer_params)
    @answer.question_id = @question.id
    @answer.user_id = current_user.id

    respond_to do |format|
      if @answer.save
        # Notification for question author
        build_answered_notification
        format.html { redirect_to @question, notice: 'Answer was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /answers/1
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @question, notice: 'Answer was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /answers/1
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to @question, notice: 'Answer was successfully destroyed.' }
    end
  end

  # POST /answers/1/upvote
  def upvote
    @answer.update(upvotes: @answer.upvotes + 1)
    # Rep for answer author
    @answer.user.update(reputation: @answer.user.reputation + 1)
    # Notification for answer author
    Notification.create(user_id: @answer.user.id, question_id: @question.id, content: 'Your answer was upvoted!  Nice job!')
    
    redirect_to question_url(@question), notice: 'Answer upvoted!'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def set_question
      @question = Question.find(params[:question_id])
    end

    def confirm_owner
      if user_signed_in?
        unless current_user.isadmin
          if Answer.find(params[:id]).user_id != current_user.id
            redirect_to questions_url, alert: 'You are not allowed to modify other user\'s answers.'
          end
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:content)
    end

    # Builds a notification for the question author that their question was answered
    def build_answered_notification
      Notification.create(user_id: @question.user.id, question_id: @question.id, content: 'Your question got a new answer!')
    end
end

finalproj/app/helpers/answers_helper.rb
module AnswersHelper
end

finalproj/app/views/answers/_answer.html.erb
<div id="answer-wrapper">
   <span id="answer-upvotes">
    <%= answer.upvotes %> <br>
    upvotes
    <% if !user_signed_in? || current_user.id != answer.user_id %>
      <%= button_to 'Upvote!', answer_upvote_path(@question,answer) %>
    <% end %>
  </span>
  <span id="answer-content">
    <%= answer.content %>
  </span>
  <span id="answer-mod-links">
    <% if !user_signed_in? || (!current_user.isadmin && current_user.id != answer.user_id) %>
      <p id="null-link"></p>
    <% end %>
  	<% if user_signed_in? && (current_user.id == answer.user_id || current_user.isadmin) %>
  	  <%= link_to 'Edit', edit_question_answer_path(@question,answer) %>
  	<% end %>
  	<% if user_signed_in? && current_user.isadmin %>
  	  <%= link_to 'Delete', question_answer_url(@question, answer), method: :delete, data: { confirm: 'Are you sure?' } %>
  	<% end %>
  </span>
  <span id="answer-author">
    <%= render answer.user %>
  </span>
</div>

finalproj/app/views/answers/_form.html.erb
<%= form_for([@question,@answer]) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, size: "75x25" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

finalproj/app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<!-- Render question for user to reference -->
<%= render @question %>
<div id="question-content">
	<br>
  <%= @question.content %>
</div>

<hr>

<%= render 'form' %>

<%= link_to 'Back', @question %>

finalproj/app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>